export default {
  namespaced: true,
  state: {
    deez: "hello",
    cataLog: [
      {
        name: "Large Frog",
        img: `${process.env.BASE_URL}photos/frog.png`,
        price: 55,
        cata: "animals",
        recc: false,
        id: 1,
      },
      {
        name: "small frog",
        img: `${process.env.BASE_URL}photos/frog-braces.png`,
        price: 12,
        cata: "animals",
        recc: false,
        id: 2,
      },
      {
        name: "Cat",
        img: `${process.env.BASE_URL}photos/cat.png`,
        price: 20,
        cata: "animals",
        recc: false,
        id: 3,
      },
      {
        name: "Yellow Car",
        img: `${process.env.BASE_URL}photos/yellow-car.png`,
        price: 250,
        cata: "cars",
        recc: true,
        id: 4,
      },
      {
        name: "Pink sock",
        img: `${process.env.BASE_URL}photos/pinksock.png`,
        price: 5,
        cata: "socks",
        recc: false,
        id: 5,
      },
      {
        name: "Green Sock",
        img: `${process.env.BASE_URL}photos/greensock.png`,
        price: 2,
        cata: "socks",
        recc: false,
        id: 6,
      },
      {
        name: "Blue Sock",
        img: `${process.env.BASE_URL}photos/bluesock.png`,
        price: 10,
        cata: "socks",
        recc: true,
        id: 7,
      },
      {
        name: "Developer",
        img: `${process.env.BASE_URL}photos/oliver.png`,
        price: 2,
        cata: "animals",
        recc: true,
        id: 8,
      },
    ],
  },
};
